### PR TITLE
STY: Change class name from SRWDetector to SirepoDetector

### PR DESCRIPTION
**Pull request by kalebswartz7**
- Changes both file and class name from SRWDetector to SirepoDetector as the program can now work with almost all Sirepo simulations.

### CODE REVIEW

**Comment by mrakitin** [comment]
Does it share the same commits as #3? This PR should have very tiny changes. Let's first finish with #3 and then create a new PR based on the new master update.

**Comment by kalebswartz7** [comment]
I didn't expect it to carry the old commits over, I created a new branch and then made the name changes but I am guessing it is because all of the old changes were still in this branch as it is up to date with my master. How should be fix this?

**Comment by mrakitin** [comment]
I guess you created a new branch based on the branch for #3, which just copied the whole history from there. Please first finish work on #3, then when it's merged, a new branch can be created from **master**, and then relevant fixes should be applied. Thanks.

**Comment by kalebswartz7** [comment]
Got it, ill work on finishing the other stuff and then we can do the name change after.

**Pull request closed without merging**
